### ISSUE TITLE
sentence tokenization 

### ISSUE THREAD

**Issue by juliettedm** [cyruslk/franklin-ford-bot#9]
> Going back to the code of last week - Something I realised is that we're running the OCR every time we're performing a fetch from the URL. This is a lot of computation and we should be able to:
> 
> 1 - Run the OCR one -- for all the texts
> 2 - Pick a random string using the split(".") operator inside a .txt file.
> 3 - Then, do the computation

Just a small thing: as you work with Watson, it probably has some kind of [sentence tokenization ](https://www.ibm.com/developerworks/community/blogs/nlp/entry/tokenization?lang=en)feature. That might be better than simply using the split(".") operator?

**Comment by cyruslk** [comment]
Added this package: https://www.npmjs.com/package/natural
